### PR TITLE
Fix typo in spelling from "Puckaun" to "Puckane"

### PR DESCRIPTION
**Pull request by cormon1976**
Correct typo.

### CODE REVIEW

**Comment by jasnell** [comment]
Thank you for the fix @cormon1976 ... it looks like there's an errant file added (codeql-analysis.yml) that should be removed before this can land. Could I ask you to fix that?

**Comment by cormon1976** [comment]
@jasnell  done.

Great work on this app btw :) seems to be well written and designed.

**Comment by jasnell** [comment]
Thank you @cormon1976 ! :-) 

/cc @colmharte

**Comment by colmharte** [comment]
The country / town lists are provided by the CSO and as checkin data is fed back to the CSO we need to keep the naming consistent with their lists.

**Pull request closed without merging**
